zshrc: remove cruft, overhaul funcs, organize
* separate into sections with #############
* remove default ohmyzsh zshrc
* add funcs
  * mkgplv3 - initialize git gplv3 project
  * hexshow - visualize colors in terminal
  * ck - poor man's taskbar (shows battery, datetime)
* remove funcs
  * remove ytw (i have a stronger solution to dodge yt's bad ui)
  * remove blacken-term (i made a quick gtk app for a black box instead)
  * remove realcd (i dont spam my home dir with symlinks anymore)
  * remove gitget (idk i just copy-paste a file i look up anyway)
  * dealias neofetch='fastfetch --config neofetch' (meh)
  * dealias yay=paru
  * dealias vim to nvim
  * dealias foliate with WEBKIT_DISABLE_DMABUF_RENDERER=1 fix (doesnt
    affect me anymore)
* source completions instead of including everything
  * $(zoxide init zsh)
* add paths for
  * cargo, flutter, bun
* remove paths for
  * pnpm
* fix ioctl error for git gpg sign with GPG_TTY env var

diff --git a/gentoo/zshrc b/gentoo/zshrc
--- a/gentoo/zshrc
+++ b/gentoo/zshrc
@@ -1,134 +1,40 @@
-# If you come from bash you might have to change your $PATH.
-export PATH="$HOME/.cargo/bin:$PATH"
-export PATH="$HOME/.local/bin:$PATH"
-
-# Path to your Oh My Zsh installation.
-export ZSH=/usr/share/oh-my-zsh
-# Set name of the theme to load --- if set to "random", it will
-# load a random theme each time Oh My Zsh is loaded, in which case,
-# to know which specific one was loaded, run: echo $RANDOM_THEME
-# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
+# oh my zsh ###################################################################
+export ZSH="/usr/share/zsh/site-contrib/oh-my-zsh"
 ZSH_THEME="netmask"
-
-# Set list of themes to pick from when loading at random
-# Setting this variable when ZSH_THEME=random will cause zsh to load
-# a theme from this variable instead of looking in $ZSH/themes/
-# If set to an empty array, this variable will have no effect.
-# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
-
-# Uncomment the following line to use case-sensitive completion.
-# CASE_SENSITIVE="true"
-
-# Uncomment the following line to use hyphen-insensitive completion.
-# Case-sensitive completion must be off. _ and - will be interchangeable.
-# HYPHEN_INSENSITIVE="true"
-
-# Uncomment one of the following lines to change the auto-update behavior
-# zstyle ':omz:update' mode disabled  # disable automatic updates
-# zstyle ':omz:update' mode auto      # update automatically without asking
-# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
-
-# Uncomment the following line to change how often to auto-update (in days).
-# zstyle ':omz:update' frequency 13
-
-# Uncomment the following line if pasting URLs and other text is messed up.
-# DISABLE_MAGIC_FUNCTIONS="true"
-
-# Uncomment the following line to disable colors in ls.
-# DISABLE_LS_COLORS="true"
-
-# Uncomment the following line to disable auto-setting terminal title.
-# DISABLE_AUTO_TITLE="true"
-
-# Uncomment the following line to enable command auto-correction.
-# ENABLE_CORRECTION="true"
-
-# Uncomment the following line to display red dots whilst waiting for completion.
-# You can also set it to another string to have that shown instead of the default red dots.
-# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
-# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
-# COMPLETION_WAITING_DOTS="true"
-
-# Uncomment the following line if you want to disable marking untracked files
-# under VCS as dirty. This makes repository status check for large repositories
-# much, much faster.
-# DISABLE_UNTRACKED_FILES_DIRTY="true"
-
-# Uncomment the following line if you want to change the command execution time
-# stamp shown in the history command output.
-# You can set one of the optional three formats:
-# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
-# or set a custom format using the strftime function format specifications,
-# see 'man strftime' for details.
-# HIST_STAMPS="mm/dd/yyyy"
-
-# Would you like to use another custom folder than $ZSH/custom?
-# ZSH_CUSTOM=/path/to/new-custom-folder
-
-# Which plugins would you like to load?
-# Standard plugins can be found in $ZSH/plugins/
-# Custom plugins may be added to $ZSH_CUSTOM/plugins/
-# Example format: plugins=(rails git textmate ruby lighthouse)
-# Add wisely, as too many plugins slow down shell startup.
 plugins=(git)
-
+EDITOR=nvim
 source $ZSH/oh-my-zsh.sh
 
-# User configuration
+# paths #######################################################################
+# cargo
+export PATH=$PATH:$HOME/.cargo/bin
+# flutter
+export PATH=$PATH:$HOME/flutter/flutter/bin
+# bun
+export BUN_INSTALL="$HOME/.bun"
+export PATH="$BUN_INSTALL/bin:$PATH"
 
-# export MANPATH="/usr/local/man:$MANPATH"
+# completions #################################################################
+eval "$(zoxide init zsh)"
+source /usr/share/zsh/site-functions/zsh-autosuggestions.zsh
+[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
 
-# You may need to manually set your language environment
-# export LANG=en_US.UTF-8
+# fixes #######################################################################
+# GPG_TTY: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=doc/gpg-agent.texi;h=42ac84019e79e9e7845a673af5e5a3e154c5ba36;hb=HEAD#l96
+#          fixes invalid ioctl error during gpg-based git sign
+export GPG_TTY=$(tty)
+# Wayland hint: https://github.com/flathub/org.signal.Signal/commit/11cc6bbe9581a8ec9ba21b96d7582ed024db7570
+#               fixes wayland-compatible electron apps from erroneously using x11
+#               NOTE: some electron apps may need --enable-gpu or --disable-gpu
+export ELECTRON_OZONE_PLATFORM_HINT=auto
 
-# Preferred editor for local and remote sessions
-# if [[ -n $SSH_CONNECTION ]]; then
-#   export EDITOR='vim'
-# else
-   export EDITOR='nvim'
-# fi
+# funcs #######################################################################
+alias py=python3
 
-# Compilation flags
-# export ARCHFLAGS="-arch $(uname -m)"
+# silly man page skip
+export tldr() {curl cht.sh/$1}
 
-# Set personal aliases, overriding those provided by Oh My Zsh libs,
-# plugins, and themes. Aliases can be placed here, though Oh My Zsh
-# users are encouraged to define aliases within a top-level file in
-# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
-# - $ZSH_CUSTOM/aliases.zsh
-# - $ZSH_CUSTOM/macos.zsh
-# For a full list of active aliases, run `alias`.
-#
-# Example aliases
-# alias zshconfig="mate ~/.zshrc"
-# alias ohmyzsh="mate ~/.oh-my-zsh"
-tldr() {
-  curl "https://cheat.sh/$1"
-}
-blacken-term(){
-  trap 'tput reset' INT
-  echo -ne "\e]12;#00000F\a"
-  clear && sleep 1e8
-}
-ytw() {
-  yt-dlp -o - "$1" | mpv --profile=fast --hwdec=auto -
-}
-realcd() {
-  cd "$(realpath $1)"
-}
-gitget() {
-  url="$(echo "$1" | awk -F'/' -v OFS='/' '{
-      $3 = "raw.githubusercontent.com";
-      $6 = "refs/heads"; 
-      print; 
-  }')"
-  wget "$url"
-}
-alias neofetch='fastfetch --config neofetch'
-alias py=python
-alias yay=paru
-alias vim=nvim
-alias foliate="env WEBKIT_DISABLE_DMABUF_RENDERER=1 foliate"
+# run a command and silently detach e.g. stfu chromium
 stfu() {
   if [ -z "$1" ]; then
     echo "Usage: stfu <program or alias> [arguments...]"
@@ -137,7 +43,7 @@ stfu() {
 
   if [[ "$(type "$1" | cut -d' ' -f2-5)" == "is a shell function" ]]; then
     # eval can be buggy with quotes; this is a backup
-    # in case we're running something like stfu stfu ls
+    # in case we're running something like `stfu stfu ls`
     eval "$@" &>/dev/null &
   else
     # alias expansion support instead of raw nohup
@@ -156,148 +62,46 @@ _stfu() {
   _normal
 }
 compdef _stfu stfu
-# bun completions
-[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
 
-# bun
-export BUN_INSTALL="$HOME/.bun"
-export PATH="$BUN_INSTALL/bin:$PATH"
-
-# pnpm
-export PNPM_HOME="$HOME/.local/share/pnpm"
-case ":$PATH:" in
-  *":$PNPM_HOME:"*) ;;
-  *) export PATH="$PNPM_HOME:$PATH" ;;
-esac
-# pnpm end
-
-
-# shellcheck shell=bash
-
-# =============================================================================
-#
-# Utility functions for zoxide.
-#
-
-# pwd based on the value of _ZO_RESOLVE_SYMLINKS.
-function __zoxide_pwd() {
-    \builtin pwd -L
+# read battery and date. poor man's taskbar
+ck() {
+  tput civis
+  trap 'tput cnorm; return 1' INT TERM
+  while true; do
+    printf "%s%% | %s" "$(cat /sys/class/power_supply/BAT0/capacity)" "$(date +"%Y-%m-%d %T %a")"
+    sleep 1;
+    printf "\r"
+  done
 }
 
-# cd + custom logic based on the value of _ZO_ECHO.
-function __zoxide_cd() {
-    # shellcheck disable=SC2164
-    \builtin cd -- "$@"
+# shows a rgb value in terminal
+hexshow() {
+  is8bit() { # inputs: any. outputs: is number in [0,255]
+    [[ "$1" =~ ^[0-9]{1,3}$ ]] && (( $1 >= 0 && $1 <= 255 ))
+  }
+  cprint() { # inputs: r g b
+    printf "\e[48;2;${1};${2};${3}m    \e[0m\n"
+    printf "\e[48;2;${1};${2};${3}m    \e[0m\n"
+  }
+  if [[ "$1" =~ ^[0-9A-Fa-f]{6}$ ]]; then
+    local color="#$1"
+    local r=$(( 16#${color:1:2} ))
+    local g=$(( 16#${color:3:2} ))
+    local b=$(( 16#${color:5:2} ))
+    cprint "$r" "$g" "$b"
+  elif is8bit "$1" && is8bit "$2" && is8bit "$3"; then
+    cprint "$1" "$2" "$3"
+  else
+    echo "Usage: hexshow RRGGBB or hexshow R G B"
+  fi
 }
 
-# =============================================================================
-#
-# Hook configuration for zoxide.
-#
-
-# Hook to add new entries to the database.
-function __zoxide_hook() {
-    # shellcheck disable=SC2312
-    \command zoxide add -- "$(__zoxide_pwd)"
+mkgplv3() {
+  set -x
+  trap 'set +x; return 1' INT TERM
+  git init
+  curl https://www.gnu.org/licenses/gpl-3.0.txt > LICENSE
+  git add LICENSE
+  git commit -m "license: add gplv3"
+  set +x
 }
-
-# Initialize hook.
-# shellcheck disable=SC2154
-if [[ ${precmd_functions[(Ie)__zoxide_hook]:-} -eq 0 ]] && [[ ${chpwd_functions[(Ie)__zoxide_hook]:-} -eq 0 ]]; then
-    chpwd_functions+=(__zoxide_hook)
-fi
-
-# =============================================================================
-#
-# When using zoxide with --no-cmd, alias these internal functions as desired.
-#
-
-# Jump to a directory using only keywords.
-function __zoxide_z() {
-    # shellcheck disable=SC2199
-    if [[ "$#" -eq 0 ]]; then
-        __zoxide_cd ~
-    elif [[ "$#" -eq 1 ]] && { [[ -d "$1" ]] || [[ "$1" = '-' ]] || [[ "$1" =~ ^[-+][0-9]$ ]]; }; then
-        __zoxide_cd "$1"
-    elif [[ "$#" -eq 2 ]] && [[ "$1" = "--" ]]; then
-        __zoxide_cd "$2"
-    else
-        \builtin local result
-        # shellcheck disable=SC2312
-        result="$(\command zoxide query --exclude "$(__zoxide_pwd)" -- "$@")" && __zoxide_cd "${result}"
-    fi
-}
-
-# Jump to a directory using interactive search.
-function __zoxide_zi() {
-    \builtin local result
-    result="$(\command zoxide query --interactive -- "$@")" && __zoxide_cd "${result}"
-}
-
-# =============================================================================
-#
-# Commands for zoxide. Disable these using --no-cmd.
-#
-
-function z() {
-    __zoxide_z "$@"
-}
-
-function zi() {
-    __zoxide_zi "$@"
-}
-
-# Completions.
-if [[ -o zle ]]; then
-    __zoxide_result=''
-
-    function __zoxide_z_complete() {
-        # Only show completions when the cursor is at the end of the line.
-        # shellcheck disable=SC2154
-        [[ "${#words[@]}" -eq "${CURRENT}" ]] || return 0
-
-        if [[ "${#words[@]}" -eq 2 ]]; then
-            # Show completions for local directories.
-            _cd -/
-
-        elif [[ "${words[-1]}" == '' ]]; then
-            # Show completions for Space-Tab.
-            # shellcheck disable=SC2086
-            __zoxide_result="$(\command zoxide query --exclude "$(__zoxide_pwd || \builtin true)" --interactive -- ${words[2,-1]})" || __zoxide_result=''
-
-            # Set a result to ensure completion doesn't re-run
-            compadd -Q ""
-
-            # Bind '\e[0n' to helper function.
-            \builtin bindkey '\e[0n' '__zoxide_z_complete_helper'
-            # Sends query device status code, which results in a '\e[0n' being sent to console input.
-            \builtin printf '\e[5n'
-
-            # Report that the completion was successful, so that we don't fall back
-            # to another completion function.
-            return 0
-        fi
-    }
-
-    function __zoxide_z_complete_helper() {
-        if [[ -n "${__zoxide_result}" ]]; then
-            # shellcheck disable=SC2034,SC2296
-            BUFFER="z ${(q-)__zoxide_result}"
-            __zoxide_result=''
-            \builtin zle reset-prompt
-            \builtin zle accept-line
-        else
-            \builtin zle reset-prompt
-        fi
-    }
-    \builtin zle -N __zoxide_z_complete_helper
-
-    [[ "${+functions[compdef]}" -ne 0 ]] && \compdef __zoxide_z_complete z
-fi
-
-# =============================================================================
-#
-# To initialize zoxide, add this to your configuration (usually ~/.zshrc):
-#
-# eval "$(zoxide init zsh)"
-
